-- Insert mock data into children_homes first because campaigns reference it
INSERT INTO children_homes (name, location, district, latitude, longitude, children_count, contact_person, phone, current_needs, description, image_url)
VALUES
  ('Sunflower Children''s Home', 'Colombo 10', 'Colombo', 6.9271, 79.8612, 45, 'Mrs. Malkanthi Perera', '+94 11 234 5678', ARRAY['clothes', 'food'], 'Providing shelter and care to abandoned and orphaned children since 1998.', '/images/home-1.jpg'),
  ('Rainbow Orphanage', 'Peradeniya Road, Kandy', 'Kandy', 7.2906, 80.6337, 32, 'Rev. Fr. Anton Silva', '+94 81 222 3344', ARRAY['school_supplies'], 'A faith-based home caring for children from difficult family backgrounds.', '/images/home-2.jpg'),
  ('Hope Haven', 'Wakwella Road, Galle', 'Southern', 6.0535, 80.221, 28, 'Ms. Kumari Jayasinghe', '+94 91 222 7890', ARRAY['medicine', 'food'], 'Supporting children from conflict-affected families in the south.', '/images/home-3.jpg'),
  ('Little Stars Home', 'Stanley Road, Jaffna', 'Northern', 9.6615, 80.0255, 38, 'Mr. K. Tharmalingam', '+94 21 222 4455', ARRAY['clothes', 'school_supplies'], 'Dedicated to rebuilding the lives of children affected by the civil conflict.', '/images/home-4.jpg'),
  ('Serenity Home', 'Inner Harbour Road, Trincomalee', 'Trincomalee', 8.5874, 81.2152, 22, 'Mrs. Nirosha Fernando', '+94 26 222 6677', ARRAY['clothes', 'food'], 'A safe haven for children who have lost one or both parents.', '/images/home-5.jpg'),
  ('Grace Children''s Village', 'Maho Road, Kurunegala', 'North Western', 7.4818, 80.3609, 55, 'Sister Mary Antonia', '+94 37 222 8899', ARRAY['school_supplies', 'medicine'], 'The largest children''s home in the North Western province.', '/images/home-6.jpg'),
  ('Sunrise Home', 'Bar Road, Batticaloa', 'Eastern', 7.7102, 81.6924, 19, 'Mr. A. Krishnarajah', '+94 65 222 1122', ARRAY['clothes'], 'Bringing hope and stability to children in the Eastern province.', '/images/home-7.jpg'),
  ('New Life Children''s Centre', 'Tangalle Road, Hambantota', 'Southern', 6.1241, 81.1185, 31, 'Ms. Dilrukshi Rathnayake', '+94 47 222 3344', ARRAY['food', 'medicine'], 'Nurturing resilient futures for children in the deep south.', '/images/home-8.jpg');

-- Insert mock data into campaigns using subqueries for children_home_id
INSERT INTO campaigns (slug, title, category, description, short_description, goal_amount, raised_amount, image_url, location, district, children_home_id, is_urgent, is_active, donor_count, days_left, created_at)
VALUES
  ('winter-clothes-trincomalee', 'Winter Clothes for Trincomalee Children''s Home', 'clothes', 'The children at Sunrise Home in Trincomalee desperately need warm clothing as temperatures drop. Many arrive with only thin cotton clothes unsuitable for the cooler months. Your donation helps us purchase jackets, sweaters, socks, and blankets for 45 children aged 4–16.', 'Help 45 children stay warm this winter.', 500000, 312000, '/images/campaign-1.jpg', 'Trincomalee', 'Trincomalee', (SELECT id FROM children_homes WHERE name = 'Serenity Home'), true, true, 87, 14, '2025-01-01'),
  ('monthly-food-colombo', 'Monthly Food Parcels — Colombo Street Kids', 'food', 'Every month, over 60 children in Colombo go to sleep hungry. Your donation funds food parcels containing rice, lentils, vegetables, milk powder, and eggs — enough for a family of four for two weeks.', 'Provide nutritious meals for 60 homeless children.', 250000, 198000, '/images/campaign-2.jpg', 'Colombo', 'Colombo', (SELECT id FROM children_homes WHERE name = 'Sunflower Children''s Home'), true, true, 134, 7, '2025-01-05'),
  ('school-books-batticaloa', 'School Books Drive 2025 — Batticaloa', 'school_supplies', 'Children in Batticaloa cannot afford school books for the new academic year. We provide complete textbook sets for Grades 1–11, plus stationery kits for each child.', 'Send 200 children to school with the books they need.', 180000, 95000, '/images/campaign-3.jpg', 'Batticaloa', 'Batticaloa', (SELECT id FROM children_homes WHERE name = 'Sunrise Home'), false, true, 56, 30, '2025-01-08'),
  ('medical-supplies-kandy', 'Medical Supplies — Kandy Children''s Ward', 'medicine', 'The Rainbow Orphanage in Kandy urgently needs OTC medicines, vitamins, and hygiene supplies. Many children arrive with untreated conditions that simple medicine can resolve.', 'Essential medicines and vitamins for 32 children.', 400000, 120000, '/images/campaign-4.jpg', 'Kandy', 'Kandy', (SELECT id FROM children_homes WHERE name = 'Rainbow Orphanage'), true, true, 43, 21, '2025-01-10'),
  ('shoes-jaffna-kids', 'Shoes for 200 Kids — Jaffna', 'clothes', 'Many children in Jaffna walk to school barefoot or in broken sandals. Proper school shoes protect feet and boost confidence in the classroom.', 'Give 200 children proper footwear for school.', 150000, 148000, '/images/campaign-5.jpg', 'Jaffna', 'Northern', (SELECT id FROM children_homes WHERE name = 'Little Stars Home'), false, true, 201, 3, '2025-01-12'),
  ('meals-hambantota', 'Nutritious Meals — Hambantota Orphanage', 'food', 'New Life Children''s Centre in Hambantota struggles to provide three meals a day. This campaign funds a balanced meal plan including protein, vegetables, and fruit for every child.', 'Feed 31 orphaned children for three months.', 300000, 87000, '/images/campaign-6.jpg', 'Hambantota', 'Hambantota', (SELECT id FROM children_homes WHERE name = 'New Life Children''s Centre'), false, true, 29, 45, '2025-01-14'),
  ('stationery-kurunegala', 'Stationery Kits for Grade 1–5 — Kurunegala', 'school_supplies', 'Grace Children''s Village needs stationery kits for the new school year — pencils, pens, rulers, erasers, and notebooks for 55 children in primary grades.', 'Pencils, pens, notebooks for 55 children.', 120000, 112000, '/images/campaign-7.jpg', 'Kurunegala', 'North Western', (SELECT id FROM children_homes WHERE name = 'Grace Children''s Village'), false, true, 78, 9, '2025-01-16'),
  ('hygiene-kits-galle', 'Sanitation & Hygiene Kits — Galle', 'medicine', 'Hope Haven in Galle needs soap, toothbrushes, sanitary products, and basic medicines. Good hygiene prevents illness and restores dignity.', 'Hygiene essentials for 28 children in Galle.', 200000, 44000, '/images/campaign-8.jpg', 'Galle', 'Southern', (SELECT id FROM children_homes WHERE name = 'Hope Haven'), false, true, 18, 60, '2025-01-18');

-- Insert mock data into sponsored_children
INSERT INTO sponsored_children (age, grade, school_name, district, items_needed, sponsorship_cost_lkr, is_sponsored)
VALUES
  (7, 2, 'Mahanama Vidyalaya', 'Colombo', ARRAY['Grade 2 Math textbook', 'Pencil case', 'School bag', 'Uniform x2'], 8500, false),
  (9, 4, 'Dharmaraja Primary', 'Kandy', ARRAY['Grade 4 Sinhala textbook', 'Science textbook', 'Notebooks x6'], 6200, false),
  (6, 1, 'Jaffna Central Primary', 'Northern', ARRAY['Grade 1 full book set', 'Pencils', 'Eraser', 'School bag', 'Water bottle'], 9800, true),
  (11, 6, 'Batticaloa Central College', 'Eastern', ARRAY['Grade 6 Science textbook', 'Math textbook', 'English workbook', 'Ruler set'], 7400, false),
  (8, 3, 'Galle Municipal Primary', 'Southern', ARRAY['Grade 3 Sinhala', 'Math', 'English textbooks', 'Pencil box'], 5900, false),
  (10, 5, 'Kurunegala Central Primary', 'North Western', ARRAY['O/L prep books', 'Grade 5 scholarship books', 'Notebooks x8'], 12000, false),
  (7, 2, 'Hambantota Primary School', 'Southern', ARRAY['Grade 2 full book set', 'School shoes', 'Uniform'], 11500, true),
  (9, 4, 'Trincomalee Primary College', 'Trincomalee', ARRAY['Grade 4 full textbook set', 'Stationery kit'], 6800, false),
  (6, 1, 'Vavuniya Primary School', 'Northern', ARRAY['Grade 1 books', 'School bag', 'Pencils', 'Crayons', 'Uniform x2'], 10200, false),
  (11, 6, 'Matara Central College', 'Southern', ARRAY['Grade 6 full science set', 'Math textbook', 'Tamil language book'], 7100, false);
