import type {
  Campaign,
  ChildrenHome,
  ImpactStory,
  SponsoredChild,
  TeamMember,
} from '@/types';

export const mockCampaigns: Campaign[] = [
  {
    id: '1',
    slug: 'winter-clothes-trincomalee',
    title: "Winter Clothes for Trincomalee Children's Home",
    category: 'clothes',
    shortDescription: 'Help 45 children stay warm this winter.',
    description:
      'The children at Sunrise Home in Trincomalee desperately need warm clothing as temperatures drop. Many arrive with only thin cotton clothes unsuitable for the cooler months. Your donation helps us purchase jackets, sweaters, socks, and blankets for 45 children aged 4–16.',
    goalAmount: 500000,
    raisedAmount: 312000,
    imageUrl: '/images/campaign-1.jpg',
    location: 'Trincomalee',
    district: 'Trincomalee',
    childrenHomeId: '5',
    isUrgent: true,
    isActive: true,
    donorCount: 87,
    daysLeft: 14,
    createdAt: '2025-01-01',
  },
  {
    id: '2',
    slug: 'monthly-food-colombo',
    title: 'Monthly Food Parcels — Colombo Street Kids',
    category: 'food',
    shortDescription: 'Provide nutritious meals for 60 homeless children.',
    description:
      'Every month, over 60 children in Colombo go to sleep hungry. Your donation funds food parcels containing rice, lentils, vegetables, milk powder, and eggs — enough for a family of four for two weeks.',
    goalAmount: 250000,
    raisedAmount: 198000,
    imageUrl: '/images/campaign-2.jpg',
    location: 'Colombo',
    district: 'Colombo',
    childrenHomeId: '1',
    isUrgent: true,
    isActive: true,
    donorCount: 134,
    daysLeft: 7,
    createdAt: '2025-01-05',
  },
  {
    id: '3',
    slug: 'school-books-batticaloa',
    title: 'School Books Drive 2025 — Batticaloa',
    category: 'school_supplies',
    shortDescription: 'Send 200 children to school with the books they need.',
    description:
      'Children in Batticaloa cannot afford school books for the new academic year. We provide complete textbook sets for Grades 1–11, plus stationery kits for each child.',
    goalAmount: 180000,
    raisedAmount: 95000,
    imageUrl: '/images/campaign-3.jpg',
    location: 'Batticaloa',
    district: 'Batticaloa',
    childrenHomeId: '7',
    isUrgent: false,
    isActive: true,
    donorCount: 56,
    daysLeft: 30,
    createdAt: '2025-01-08',
  },
  {
    id: '4',
    slug: 'medical-supplies-kandy',
    title: "Medical Supplies — Kandy Children's Ward",
    category: 'medicine',
    shortDescription: 'Essential medicines and vitamins for 32 children.',
    description:
      'The Rainbow Orphanage in Kandy urgently needs OTC medicines, vitamins, and hygiene supplies. Many children arrive with untreated conditions that simple medicine can resolve.',
    goalAmount: 400000,
    raisedAmount: 120000,
    imageUrl: '/images/campaign-4.jpg',
    location: 'Kandy',
    district: 'Kandy',
    childrenHomeId: '2',
    isUrgent: true,
    isActive: true,
    donorCount: 43,
    daysLeft: 21,
    createdAt: '2025-01-10',
  },
  {
    id: '5',
    slug: 'shoes-jaffna-kids',
    title: 'Shoes for 200 Kids — Jaffna',
    category: 'clothes',
    shortDescription: 'Give 200 children proper footwear for school.',
    description:
      'Many children in Jaffna walk to school barefoot or in broken sandals. Proper school shoes protect feet and boost confidence in the classroom.',
    goalAmount: 150000,
    raisedAmount: 148000,
    imageUrl: '/images/campaign-5.jpg',
    location: 'Jaffna',
    district: 'Northern',
    childrenHomeId: '4',
    isUrgent: false,
    isActive: true,
    donorCount: 201,
    daysLeft: 3,
    createdAt: '2025-01-12',
  },
  {
    id: '6',
    slug: 'meals-hambantota',
    title: "Nutritious Meals — Hambantota Orphanage",
    category: 'food',
    shortDescription: 'Feed 31 orphaned children for three months.',
    description:
      "New Life Children's Centre in Hambantota struggles to provide three meals a day. This campaign funds a balanced meal plan including protein, vegetables, and fruit for every child.",
    goalAmount: 300000,
    raisedAmount: 87000,
    imageUrl: '/images/campaign-6.jpg',
    location: 'Hambantota',
    district: 'Hambantota',
    childrenHomeId: '8',
    isUrgent: false,
    isActive: true,
    donorCount: 29,
    daysLeft: 45,
    createdAt: '2025-01-14',
  },
  {
    id: '7',
    slug: 'stationery-kurunegala',
    title: 'Stationery Kits for Grade 1–5 — Kurunegala',
    category: 'school_supplies',
    shortDescription: 'Pencils, pens, notebooks for 55 children.',
    description:
      "Grace Children's Village needs stationery kits for the new school year — pencils, pens, rulers, erasers, and notebooks for 55 children in primary grades.",
    goalAmount: 120000,
    raisedAmount: 112000,
    imageUrl: '/images/campaign-7.jpg',
    location: 'Kurunegala',
    district: 'North Western',
    childrenHomeId: '6',
    isUrgent: false,
    isActive: true,
    donorCount: 78,
    daysLeft: 9,
    createdAt: '2025-01-16',
  },
  {
    id: '8',
    slug: 'hygiene-kits-galle',
    title: 'Sanitation & Hygiene Kits — Galle',
    category: 'medicine',
    shortDescription: 'Hygiene essentials for 28 children in Galle.',
    description:
      'Hope Haven in Galle needs soap, toothbrushes, sanitary products, and basic medicines. Good hygiene prevents illness and restores dignity.',
    goalAmount: 200000,
    raisedAmount: 44000,
    imageUrl: '/images/campaign-8.jpg',
    location: 'Galle',
    district: 'Southern',
    childrenHomeId: '3',
    isUrgent: false,
    isActive: true,
    donorCount: 18,
    daysLeft: 60,
    createdAt: '2025-01-18',
  },
];

export const mockHomes: ChildrenHome[] = [
  {
    id: '1',
    name: "Sunflower Children's Home",
    location: 'Colombo 10',
    district: 'Colombo',
    latitude: 6.9271,
    longitude: 79.8612,
    childrenCount: 45,
    contactPerson: 'Mrs. Malkanthi Perera',
    phone: '+94 11 234 5678',
    currentNeeds: ['clothes', 'food'],
    description:
      'Providing shelter and care to abandoned and orphaned children since 1998.',
    imageUrl: '/images/home-1.jpg',
  },
  {
    id: '2',
    name: 'Rainbow Orphanage',
    location: 'Peradeniya Road, Kandy',
    district: 'Kandy',
    latitude: 7.2906,
    longitude: 80.6337,
    childrenCount: 32,
    contactPerson: 'Rev. Fr. Anton Silva',
    phone: '+94 81 222 3344',
    currentNeeds: ['school_supplies'],
    description:
      'A faith-based home caring for children from difficult family backgrounds.',
    imageUrl: '/images/home-2.jpg',
  },
  {
    id: '3',
    name: 'Hope Haven',
    location: 'Wakwella Road, Galle',
    district: 'Southern',
    latitude: 6.0535,
    longitude: 80.221,
    childrenCount: 28,
    contactPerson: 'Ms. Kumari Jayasinghe',
    phone: '+94 91 222 7890',
    currentNeeds: ['medicine', 'food'],
    description:
      'Supporting children from conflict-affected families in the south.',
    imageUrl: '/images/home-3.jpg',
  },
  {
    id: '4',
    name: 'Little Stars Home',
    location: 'Stanley Road, Jaffna',
    district: 'Northern',
    latitude: 9.6615,
    longitude: 80.0255,
    childrenCount: 38,
    contactPerson: 'Mr. K. Tharmalingam',
    phone: '+94 21 222 4455',
    currentNeeds: ['clothes', 'school_supplies'],
    description:
      'Dedicated to rebuilding the lives of children affected by the civil conflict.',
    imageUrl: '/images/home-4.jpg',
  },
  {
    id: '5',
    name: 'Serenity Home',
    location: 'Inner Harbour Road, Trincomalee',
    district: 'Trincomalee',
    latitude: 8.5874,
    longitude: 81.2152,
    childrenCount: 22,
    contactPerson: 'Mrs. Nirosha Fernando',
    phone: '+94 26 222 6677',
    currentNeeds: ['clothes', 'food'],
    description: 'A safe haven for children who have lost one or both parents.',
    imageUrl: '/images/home-5.jpg',
  },
  {
    id: '6',
    name: "Grace Children's Village",
    location: 'Maho Road, Kurunegala',
    district: 'North Western',
    latitude: 7.4818,
    longitude: 80.3609,
    childrenCount: 55,
    contactPerson: 'Sister Mary Antonia',
    phone: '+94 37 222 8899',
    currentNeeds: ['school_supplies', 'medicine'],
    description: "The largest children's home in the North Western province.",
    imageUrl: '/images/home-6.jpg',
  },
  {
    id: '7',
    name: 'Sunrise Home',
    location: 'Bar Road, Batticaloa',
    district: 'Eastern',
    latitude: 7.7102,
    longitude: 81.6924,
    childrenCount: 19,
    contactPerson: 'Mr. A. Krishnarajah',
    phone: '+94 65 222 1122',
    currentNeeds: ['clothes'],
    description:
      'Bringing hope and stability to children in the Eastern province.',
    imageUrl: '/images/home-7.jpg',
  },
  {
    id: '8',
    name: "New Life Children's Centre",
    location: 'Tangalle Road, Hambantota',
    district: 'Southern',
    latitude: 6.1241,
    longitude: 81.1185,
    childrenCount: 31,
    contactPerson: 'Ms. Dilrukshi Rathnayake',
    phone: '+94 47 222 3344',
    currentNeeds: ['food', 'medicine'],
    description:
      'Nurturing resilient futures for children in the deep south.',
    imageUrl: '/images/home-8.jpg',
  },
];

export const mockSponsoredChildren: SponsoredChild[] = [
  {
    id: 'c1',
    age: 7,
    grade: 2,
    schoolName: 'Mahanama Vidyalaya',
    district: 'Colombo',
    itemsNeeded: ['Grade 2 Math textbook', 'Pencil case', 'School bag', 'Uniform x2'],
    sponsorshipCostLKR: 8500,
    isSponsored: false,
  },
  {
    id: 'c2',
    age: 9,
    grade: 4,
    schoolName: 'Dharmaraja Primary',
    district: 'Kandy',
    itemsNeeded: ['Grade 4 Sinhala textbook', 'Science textbook', 'Notebooks x6'],
    sponsorshipCostLKR: 6200,
    isSponsored: false,
  },
  {
    id: 'c3',
    age: 6,
    grade: 1,
    schoolName: 'Jaffna Central Primary',
    district: 'Northern',
    itemsNeeded: ['Grade 1 full book set', 'Pencils', 'Eraser', 'School bag', 'Water bottle'],
    sponsorshipCostLKR: 9800,
    isSponsored: true,
  },
  {
    id: 'c4',
    age: 11,
    grade: 6,
    schoolName: 'Batticaloa Central College',
    district: 'Eastern',
    itemsNeeded: ['Grade 6 Science textbook', 'Math textbook', 'English workbook', 'Ruler set'],
    sponsorshipCostLKR: 7400,
    isSponsored: false,
  },
  {
    id: 'c5',
    age: 8,
    grade: 3,
    schoolName: 'Galle Municipal Primary',
    district: 'Southern',
    itemsNeeded: ['Grade 3 Sinhala', 'Math', 'English textbooks', 'Pencil box'],
    sponsorshipCostLKR: 5900,
    isSponsored: false,
  },
  {
    id: 'c6',
    age: 10,
    grade: 5,
    schoolName: 'Kurunegala Central Primary',
    district: 'North Western',
    itemsNeeded: ['O/L prep books', 'Grade 5 scholarship books', 'Notebooks x8'],
    sponsorshipCostLKR: 12000,
    isSponsored: false,
  },
  {
    id: 'c7',
    age: 7,
    grade: 2,
    schoolName: 'Hambantota Primary School',
    district: 'Southern',
    itemsNeeded: ['Grade 2 full book set', 'School shoes', 'Uniform'],
    sponsorshipCostLKR: 11500,
    isSponsored: true,
  },
  {
    id: 'c8',
    age: 9,
    grade: 4,
    schoolName: 'Trincomalee Primary College',
    district: 'Trincomalee',
    itemsNeeded: ['Grade 4 full textbook set', 'Stationery kit'],
    sponsorshipCostLKR: 6800,
    isSponsored: false,
  },
  {
    id: 'c9',
    age: 6,
    grade: 1,
    schoolName: 'Vavuniya Primary School',
    district: 'Northern',
    itemsNeeded: ['Grade 1 books', 'School bag', 'Pencils', 'Crayons', 'Uniform x2'],
    sponsorshipCostLKR: 10200,
    isSponsored: false,
  },
  {
    id: 'c10',
    age: 11,
    grade: 6,
    schoolName: 'Matara Central College',
    district: 'Southern',
    itemsNeeded: ['Grade 6 full science set', 'Math textbook', 'Tamil language book'],
    sponsorshipCostLKR: 7100,
    isSponsored: false,
  },
];

export const mockImpactStories: ImpactStory[] = [
  {
    id: 's1',
    firstName: 'Amali',
    age: 9,
    location: 'Colombo',
    quote:
      'Now I can go to school with new books. My teacher says I am the best in class!',
    fullStory:
      'Amali lost her father when she was five. Her mother works as a daily labourer and could not afford school books. Through Compassion Lanka\'s Education First program, Amali received a complete textbook set and stationery kit. She now attends school every day and has risen to the top of her class.',
    imageUrl: '/images/story-1.jpg',
    program: 'school_supplies',
  },
  {
    id: 's2',
    firstName: 'Nuwan',
    age: 7,
    location: 'Kandy',
    quote: 'I have warm clothes now. I am not cold when I sleep anymore.',
    fullStory:
      'Nuwan arrived at Rainbow Orphanage with only the clothes on his back — a thin t-shirt and shorts. During the monsoon season, he shivered every night. Donors from Australia sent a bale of winter clothing that included jackets and blankets sized for Nuwan. He sleeps warmly now and smiles every morning.',
    imageUrl: '/images/story-2.jpg',
    program: 'clothes',
  },
  {
    id: 's3',
    firstName: 'Kavitha',
    age: 11,
    location: 'Jaffna',
    quote: 'The vitamins made me stronger. I have not been sick for six months!',
    fullStory:
      'Kavitha was frequently ill due to malnutrition when she first came to Little Stars Home. Our Medical Aid program provided daily vitamin supplements and regular health check-ups. Six months later, Kavitha is healthy, active, and excelling in her studies.',
    imageUrl: '/images/story-3.jpg',
    program: 'medicine',
  },
];

export const mockTeamMembers: TeamMember[] = [
  {
    id: 't1',
    name: 'Priya Wickramasinghe',
    role: 'Executive Director',
    bio: 'Social worker with 20 years experience in child welfare across Sri Lanka.',
    avatarUrl: '/images/team-1.jpg',
  },
  {
    id: 't2',
    name: 'Rohan Fernando',
    role: 'Operations Manager',
    bio: 'Former UNICEF coordinator managing distribution to 50+ partner homes.',
    avatarUrl: '/images/team-2.jpg',
  },
  {
    id: 't3',
    name: 'Dilani Seneviratne',
    role: 'Partnerships & Outreach',
    bio: 'Connecting international donors with local communities since 2015.',
    avatarUrl: '/images/team-3.jpg',
  },
  {
    id: 't4',
    name: 'Kasun Jayawardena',
    role: 'Finance & Compliance',
    bio: 'Chartered accountant ensuring full transparency in all fund usage.',
    avatarUrl: '/images/team-4.jpg',
  },
];

export const impactStats = {
  totalDonors: 4821,
  childrenHelped: 12400,
  goodsPackagesReceived: 892,
  activeCampaigns: 8,
  countriesReached: 34,
  homesPartnered: 47,
};

export const mockDonors = [
  { name: 'Sarah M.', amount: 5000, date: '2025-01-20', anonymous: false },
  { name: 'Anonymous', amount: 10000, date: '2025-01-19', anonymous: true },
  { name: 'James T.', amount: 2500, date: '2025-01-18', anonymous: false },
  { name: 'Maria L.', amount: 1000, date: '2025-01-17', anonymous: false },
  { name: 'Anonymous', amount: 50000, date: '2025-01-16', anonymous: true },
  { name: 'David K.', amount: 2500, date: '2025-01-15', anonymous: false },
  { name: 'Emma W.', amount: 5000, date: '2025-01-14', anonymous: false },
  { name: 'Raj P.', amount: 1000, date: '2025-01-13', anonymous: false },
  { name: 'Anonymous', amount: 15000, date: '2025-01-12', anonymous: true },
  { name: 'Lisa H.', amount: 2000, date: '2025-01-11', anonymous: false },
];

export const mockDashboardDonations = [
  {
    id: 'd1',
    campaign: 'Winter Clothes for Trincomalee',
    amount: 5000,
    date: '2025-01-15',
    status: 'completed' as const,
  },
  {
    id: 'd2',
    campaign: 'Monthly Food Parcels — Colombo',
    amount: 10000,
    date: '2024-12-20',
    status: 'completed' as const,
  },
  {
    id: 'd3',
    campaign: 'School Books Drive 2025',
    amount: 2500,
    date: '2024-11-05',
    status: 'completed' as const,
  },
];

export const mockDashboardShipments = [
  {
    id: 's1',
    contents: 'Winter clothes and blankets',
    status: 'received' as const,
    date: '2025-01-10',
  },
  {
    id: 's2',
    contents: 'School books and stationery',
    status: 'in_transit' as const,
    date: '2025-01-18',
  },
];

export const GOODS_ADDRESS = {
  name: 'Compassion Lanka Foundation',
  line1: 'No. 42, Baudhaloka Mawatha',
  line2: 'Colombo 07, Sri Lanka',
  phone: '+94 11 234 5678',
  email: 'goods@compassionlanka.org',
};
